name: outreach-cookbooks-dev
channels:
  - conda-forge
  - pyviz
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server<2
  - xarray
  - pandas
  - metpy
  - dask
  - hvplot
  - s3fs
  - pip
  - pip:
      - sphinx-pythia-theme
      - sage-data-client
